spring:
  application:
    name: hhhhhhjs-ai-backend
server:
  port: 1218
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.aibyhhhhhhjs.controller # ???????
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
